spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://mysql/shadowsocks?serverTimezone=Asia/Shanghai
    username: root
    password: toor
  redis:
    host: redis
    port: 6379
    password: toor
    database: 0
